//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Contact.
        /// </summary>
        internal static string AddContactButton {
            get {
                return ResourceManager.GetString("AddContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        internal static string AddContactPage_Button_AddContact {
            get {
                return ResourceManager.GetString("AddContactPage_Button_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string AddContactPage_Label_Guid {
            get {
                return ResourceManager.GetString("AddContactPage_Label_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AddContactPage_Label_Name {
            get {
                return ResourceManager.GetString("AddContactPage_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        internal static string AddContactPage_Title {
            get {
                return ResourceManager.GetString("AddContactPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Conversation.
        /// </summary>
        internal static string AddConversationButton {
            get {
                return ResourceManager.GetString("AddConversationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: Street, City State.
        /// </summary>
        internal static string AddressStreetCityState {
            get {
                return ResourceManager.GetString("AddressStreetCityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat/Verify.
        /// </summary>
        internal static string ChatVerify {
            get {
                return ResourceManager.GetString("ChatVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Location.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map/PinInfoPage.
        /// </summary>
        internal static string MapInfo {
            get {
                return ResourceManager.GetString("MapInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map/PinScrollPage.
        /// </summary>
        internal static string MapPinScrollPage {
            get {
                return ResourceManager.GetString("MapPinScrollPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        internal static string Medical {
            get {
                return ResourceManager.GetString("Medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Pin.
        /// </summary>
        internal static string MedicalPin {
            get {
                return ResourceManager.GetString("MedicalPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Information.
        /// </summary>
        internal static string PinInformation {
            get {
                return ResourceManager.GetString("PinInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        internal static string Pins {
            get {
                return ResourceManager.GetString("Pins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Type.
        /// </summary>
        internal static string PinType {
            get {
                return ResourceManager.GetString("PinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contact.
        /// </summary>
        internal static string SelectContact {
            get {
                return ResourceManager.GetString("SelectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter.
        /// </summary>
        internal static string Shelter {
            get {
                return ResourceManager.GetString("Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelter Pin.
        /// </summary>
        internal static string ShelterPin {
            get {
                return ResourceManager.GetString("ShelterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies.
        /// </summary>
        internal static string Supplies {
            get {
                return ResourceManager.GetString("Supplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Pin.
        /// </summary>
        internal static string SupplyPin {
            get {
                return ResourceManager.GetString("SupplyPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
